; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG218132 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG218133 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG218134 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG216303 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG216304 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG216305 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG217488 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG217489 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217490 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG216625 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG216626 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG216627 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_CycleStepSetting@@3Uqt_meta_stringdata_CycleStepSetting_t@@B DD 0ffffffffH ; qt_meta_stringdata_CycleStepSetting
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000150H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	0000000000000149H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000140H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000129H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000123H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000116H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	000000000000010bH
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000100H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000000f6H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	00000000000000ebH
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	00000000000000dfH
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	00000000000000d5H
	DD	0ffffffffH
	DD	03H
	DD	00H
	ORG $+4
	DQ	00000000000000cbH
	DD	0ffffffffH
	DD	03H
	DD	00H
	ORG $+4
	DQ	00000000000000b7H
	DB	'CycleStepSetting', 00H, 'onButtonAddCol', 00H, 00H, 'onB'
	DB	'uttonDeleteCol', 00H, 'onButtonUp', 00H, 'onButtonDown', 00H, 'o'
	DB	'nButtonLeft', 00H, 'onButtonRight', 00H, 'onButtonSure', 00H, 'o'
	DB	'nButtonAdd', 00H, 'onButtonMinus', 00H, 'onItemChanged', 00H, 'r'
	DB	'ow', 00H, 'col', 00H
	ORG $+5
$SG217810 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG217811 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG217812 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_CycleStepSetting@@3QBIB DD 08H		; qt_meta_data_CycleStepSetting
	DD	00H
	DD	00H
	DD	00H
	DD	0aH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	040H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	041H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	042H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	043H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	044H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	045H
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	046H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	047H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	048H
	DD	02H
	DD	08H
	DD	0bH
	DD	02H
	DD	049H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02H
	DD	02H
	DD	0cH
	DD	0dH
	DD	00H
	ORG $+4
$SG218875 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG218876 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG218877 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG215981 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG215982 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG215983 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ ; CycleStepSetting::metaObject
PUBLIC	?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z	; CycleStepSetting::qt_metacast
PUBLIC	?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; CycleStepSetting::qt_metacall
PUBLIC	?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleStepSetting::qt_static_metacall
PUBLIC	?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B ; CycleStepSetting::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onButtonAddCol@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonAddCol
EXTRN	?onButtonDeleteCol@CycleStepSetting@@AEAAXXZ:PROC ; CycleStepSetting::onButtonDeleteCol
EXTRN	?onButtonUp@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonUp
EXTRN	?onButtonDown@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonDown
EXTRN	?onButtonLeft@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonLeft
EXTRN	?onButtonRight@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonRight
EXTRN	?onButtonSure@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonSure
EXTRN	?onButtonAdd@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonAdd
EXTRN	?onButtonMinus@CycleStepSetting@@AEAAXXZ:PROC	; CycleStepSetting::onButtonMinus
EXTRN	?onItemChanged@CycleStepSetting@@AEAAXHH@Z:PROC	; CycleStepSetting::onItemChanged
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B DB 030H DUP (?) ; CycleStepSetting::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN18
	DD	imagerel $LN18+300
	DD	imagerel $unwind$?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@CycleStepSetting@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@CycleStepSetting@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'CycleStepSetting::staticMetaObject'', COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 120
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B, rax
; Line 121
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_CycleStepSetting@@3Uqt_meta_stringdata_CycleStepSetting_t@@B
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B+8, rax
; Line 122
	lea	rax, OFFSET FLAT:?qt_meta_data_CycleStepSetting@@3QBIB
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B+16, rax
; Line 123
	lea	rax, OFFSET FLAT:?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleStepSetting::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B+24, rax
; Line 124
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B+32, 0
; Line 125
	mov	QWORD PTR ?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'CycleStepSetting::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; CycleStepSetting::qt_static_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 99
$LN18:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 100
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 101
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 103
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 9
	ja	$LN15@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN17@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 104
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonAddCol@CycleStepSetting@@AEAAXXZ ; CycleStepSetting::onButtonAddCol
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 105
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonDeleteCol@CycleStepSetting@@AEAAXXZ ; CycleStepSetting::onButtonDeleteCol
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 106
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonUp@CycleStepSetting@@AEAAXXZ	; CycleStepSetting::onButtonUp
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 107
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonDown@CycleStepSetting@@AEAAXXZ	; CycleStepSetting::onButtonDown
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 108
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonLeft@CycleStepSetting@@AEAAXXZ	; CycleStepSetting::onButtonLeft
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 109
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonRight@CycleStepSetting@@AEAAXXZ ; CycleStepSetting::onButtonRight
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 110
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonSure@CycleStepSetting@@AEAAXXZ	; CycleStepSetting::onButtonSure
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 111
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonAdd@CycleStepSetting@@AEAAXXZ	; CycleStepSetting::onButtonAdd
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 112
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonMinus@CycleStepSetting@@AEAAXXZ ; CycleStepSetting::onButtonMinus
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 113
	mov	eax, 8
	imul	rax, rax, 2
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, 8
	imul	rcx, rcx, 1
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	r8d, DWORD PTR [rax]
	mov	edx, DWORD PTR [rcx]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onItemChanged@CycleStepSetting@@AEAAXHH@Z ; CycleStepSetting::onItemChanged
$LN15@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 117
	add	rsp, 56					; 00000038H
	ret	0
	npad	3
$LN17@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CycleStepSetting::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; CycleStepSetting::qt_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 143
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 144
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 145
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 146
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 147
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 148
	cmp	DWORD PTR _id$[rsp], 10
	jge	SHORT $LN5@qt_metacal
; Line 149
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@CycleStepSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleStepSetting::qt_static_metacall
$LN5@qt_metacal:
; Line 150
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 10
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 151
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 152
	cmp	DWORD PTR _id$[rsp], 10
	jge	SHORT $LN7@qt_metacal
; Line 153
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 154
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 10
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 156
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 157
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@CycleStepSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CycleStepSetting::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z PROC	; CycleStepSetting::qt_metacast
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 135
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 136
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 137
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_CycleStepSetting@@3Uqt_meta_stringdata_CycleStepSetting_t@@B+336
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 138
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 139
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 140
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@CycleStepSetting@@UEAAPEAXPEBD@Z ENDP	; CycleStepSetting::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ PROC ; CycleStepSetting::metaObject
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 130
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 131
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@CycleStepSetting@@2UQMetaObject@@B ; CycleStepSetting::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 132
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@CycleStepSetting@@UEBAPEBUQMetaObject@@XZ ENDP ; CycleStepSetting::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.12.3\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 160
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclestepsetting.cpp
; Line 160
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
