; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG202982 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG202983 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG202984 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG203304 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG203305 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG203306 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG204541 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG204542 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG204543 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_DelaySetting@@3Uqt_meta_stringdata_DelaySetting_t@@B DD 0ffffffffH ; qt_meta_stringdata_DelaySetting
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000168H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	000000000000015dH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000157H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000140H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000013cH
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000137H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000131H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000012aH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000123H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	000000000000011eH
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000118H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000112H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000010bH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000106H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000101H
	DB	'DelaySetting', 00H, 'buttonSureClicked', 00H, 00H, 'butt'
	DB	'onSwitchClicked', 00H, 'buttonClearClicked', 00H, 'buttonZero'
	DB	'Clicked', 00H, 'buttonOneClicked', 00H, 'buttonTwoClicked', 00H
	DB	'buttonThreeClicked', 00H, 'buttonFourClicked', 00H, 'buttonFi'
	DB	'veClicked', 00H, 'buttonSixClicked', 00H, 'buttonSevenClicked'
	DB	00H, 'buttonEightClicked', 00H, 'buttonNineClicked', 00H
	ORG $+5
$SG202660 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG202661 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG202662 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_DelaySetting@@3QBIB DD 08H		; qt_meta_data_DelaySetting
	DD	00H
	DD	00H
	DD	00H
	DD	0dH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	04fH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	050H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	051H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	052H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	053H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	054H
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	055H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	056H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	057H
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	058H
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	059H
	DD	02H
	DD	08H
	DD	0dH
	DD	00H
	DD	05aH
	DD	02H
	DD	08H
	DD	0eH
	DD	00H
	DD	05bH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ ; DelaySetting::metaObject
PUBLIC	?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z	; DelaySetting::qt_metacast
PUBLIC	?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; DelaySetting::qt_metacall
PUBLIC	?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DelaySetting::qt_static_metacall
PUBLIC	?staticMetaObject@DelaySetting@@2UQMetaObject@@B ; DelaySetting::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?buttonSureClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonSureClicked
EXTRN	?buttonSwitchClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonSwitchClicked
EXTRN	?buttonClearClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonClearClicked
EXTRN	?buttonZeroClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonZeroClicked
EXTRN	?buttonOneClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonOneClicked
EXTRN	?buttonTwoClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonTwoClicked
EXTRN	?buttonThreeClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonThreeClicked
EXTRN	?buttonFourClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonFourClicked
EXTRN	?buttonFiveClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonFiveClicked
EXTRN	?buttonSixClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonSixClicked
EXTRN	?buttonSevenClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonSevenClicked
EXTRN	?buttonEightClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonEightClicked
EXTRN	?buttonNineClicked@DelaySetting@@AEAAXXZ:PROC	; DelaySetting::buttonNineClicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@DelaySetting@@2UQMetaObject@@B DB 030H DUP (?) ; DelaySetting::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN21
	DD	imagerel $LN21+304
	DD	imagerel $unwind$?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@DelaySetting@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@DelaySetting@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@DelaySetting@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@DelaySetting@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@DelaySetting@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'DelaySetting::staticMetaObject'', COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 133
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B, rax
; Line 134
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_DelaySetting@@3Uqt_meta_stringdata_DelaySetting_t@@B
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B+8, rax
; Line 135
	lea	rax, OFFSET FLAT:?qt_meta_data_DelaySetting@@3QBIB
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B+16, rax
; Line 136
	lea	rax, OFFSET FLAT:?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DelaySetting::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B+24, rax
; Line 137
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B+32, 0
; Line 138
	mov	QWORD PTR ?staticMetaObject@DelaySetting@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@DelaySetting@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'DelaySetting::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; DelaySetting::qt_static_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 108
$LN21:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 109
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 110
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 112
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 12
	ja	$LN18@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN20@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 113
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSureClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonSureClicked
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 114
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSwitchClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonSwitchClicked
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 115
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonClearClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonClearClicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 116
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonZeroClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonZeroClicked
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 117
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonOneClicked@DelaySetting@@AEAAXXZ	; DelaySetting::buttonOneClicked
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 118
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonTwoClicked@DelaySetting@@AEAAXXZ	; DelaySetting::buttonTwoClicked
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 119
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonThreeClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonThreeClicked
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 120
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonFourClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonFourClicked
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 121
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonFiveClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonFiveClicked
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 122
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSixClicked@DelaySetting@@AEAAXXZ	; DelaySetting::buttonSixClicked
	jmp	SHORT $LN2@qt_static_
$LN15@qt_static_:
; Line 123
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSevenClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonSevenClicked
	jmp	SHORT $LN2@qt_static_
$LN16@qt_static_:
; Line 124
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonEightClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonEightClicked
	jmp	SHORT $LN2@qt_static_
$LN17@qt_static_:
; Line 125
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonNineClicked@DelaySetting@@AEAAXXZ ; DelaySetting::buttonNineClicked
$LN18@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 130
	add	rsp, 56					; 00000038H
	ret	0
$LN20@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DelaySetting::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; DelaySetting::qt_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 156
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 157
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 158
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 159
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 160
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 161
	cmp	DWORD PTR _id$[rsp], 13
	jge	SHORT $LN5@qt_metacal
; Line 162
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@DelaySetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DelaySetting::qt_static_metacall
$LN5@qt_metacal:
; Line 163
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 13
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 164
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 165
	cmp	DWORD PTR _id$[rsp], 13
	jge	SHORT $LN7@qt_metacal
; Line 166
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 167
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 13
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 169
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 170
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@DelaySetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DelaySetting::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z PROC		; DelaySetting::qt_metacast
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 148
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 149
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 150
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_DelaySetting@@3Uqt_meta_stringdata_DelaySetting_t@@B+360
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 151
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 152
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 153
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@DelaySetting@@UEAAPEAXPEBD@Z ENDP		; DelaySetting::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ PROC	; DelaySetting::metaObject
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 143
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 144
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@DelaySetting@@2UQMetaObject@@B ; DelaySetting::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 145
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@DelaySetting@@UEBAPEBUQMetaObject@@XZ ENDP	; DelaySetting::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.12.3\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 173
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_delaysetting.cpp
; Line 173
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
