; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG211977 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG211978 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG211979 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_IOService@@3Uqt_meta_stringdata_IOService_t@@B DD 0ffffffffH ; qt_meta_stringdata_IOService
	DD	09H
	DD	00H
	ORG $+4
	DQ	00000000000006a8H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000069aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000695H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000067eH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000679H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000674H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000671H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000066dH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000669H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000664H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000661H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000065eH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000065aH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000656H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000654H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000651H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000064eH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000064aH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000648H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000646H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	000000000000063cH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000633H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000626H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000624H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000612H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000610H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000610H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	000000000000060fH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000060eH
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	000000000000060cH
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	000000000000060cH
	DD	0ffffffffH
	DD	01bH
	DD	00H
	ORG $+4
	DQ	000000000000060cH
	DD	0ffffffffH
	DD	01bH
	DD	00H
	ORG $+4
	DQ	0000000000000610H
	DD	0ffffffffH
	DD	01dH
	DD	00H
	ORG $+4
	DQ	0000000000000614H
	DD	0ffffffffH
	DD	01cH
	DD	00H
	ORG $+4
	DQ	000000000000061aH
	DD	0ffffffffH
	DD	01cH
	DD	00H
	ORG $+4
	DQ	000000000000061fH
	DD	0ffffffffH
	DD	01bH
	DD	00H
	ORG $+4
	DQ	0000000000000624H
	DD	0ffffffffH
	DD	01dH
	DD	00H
	ORG $+4
	DQ	0000000000000628H
	DD	0ffffffffH
	DD	01dH
	DD	00H
	ORG $+4
	DQ	000000000000062eH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000634H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000630H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000062cH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	000000000000062aH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000627H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000624H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000620H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	000000000000061eH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000061cH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000617H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000612H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000060fH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	000000000000060bH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000607H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000602H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000005ffH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000005fcH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000005f8H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	00000000000005f4H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000005f2H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000005efH
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000005ecH
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	00000000000005e8H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	00000000000005e6H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	00000000000005e4H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	00000000000005e4H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	00000000000005e4H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	00000000000005e6H
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	00000000000005e7H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	00000000000005e8H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	00000000000005e8H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	00000000000005eaH
	DB	'IOService', 00H, 'buttonApplyClicked', 00H, 00H, 'nameIn'
	DB	'putOneModify', 00H, 'nameInputTwoModify', 00H, 'nameInputThre'
	DB	'eModify', 00H, 'nameInputFourModify', 00H, 'nameInputFiveModi'
	DB	'fy', 00H, 'nameInputSixModify', 00H, 'nameInputSevenModify', 00H
	DB	'nameInputEightModify', 00H, 'nameOutputOneModify', 00H, 'name'
	DB	'OutputTwoModify', 00H, 'nameOutputThreeModify', 00H, 'nameOut'
	DB	'putFourModify', 00H, 'nameOutputFiveModify', 00H, 'nameOutput'
	DB	'SixModify', 00H, 'nameOutputSevenModify', 00H, 'nameOutputEig'
	DB	'htModify', 00H, 'localIPModify', 00H, 'serverIPModify', 00H, 'p'
	DB	'ortModify', 00H, 'statusOutputOneModify', 00H, 'state', 00H, 's'
	DB	'tatusOutputTwoModify', 00H, 'statusOutputThreeModify', 00H, 's'
	DB	'tatusOutputFourModify', 00H, 'statusOutputFiveModify', 00H, 's'
	DB	'tatusOutputSixModify', 00H, 'statusOutputSevenModify', 00H, 's'
	DB	'tatusOutputEightModify', 00H, 'statusInitialInputOneModify', 00H
	DB	'statusInitialInputTwoModify', 00H, 'statusInitialInputThreeMo'
	DB	'dify', 00H, 'statusInitialInputFourModify', 00H, 'statusIniti'
	DB	'alInputFiveModify', 00H, 'statusInitialInputSixModify', 00H, 's'
	DB	'tatusInitialInputSevenModify', 00H, 'statusInitialInputEightM'
	DB	'odify', 00H, 'statusMenuOneModify', 00H, 'statusMenuTwoModify'
	DB	00H, 'statusMenuThreeModify', 00H, 'statusMenuFourModify', 00H
	DB	'statusMenuFiveModify', 00H, 'statusMenuSixModify', 00H, 'stat'
	DB	'usMenuSevenModify', 00H, 'statusMenuEightModify', 00H, 'statu'
	DB	'sRunOneModify', 00H, 'statusRunTwoModify', 00H, 'statusRunThr'
	DB	'eeModify', 00H, 'statusRunFourModify', 00H, 'statusRunFiveMod'
	DB	'ify', 00H, 'statusRunSixModify', 00H, 'statusRunSevenModify', 00H
	DB	'statusRunEightModify', 00H, 'statusStopOneModify', 00H, 'stat'
	DB	'usStopTwoModify', 00H, 'statusStopThreeModify', 00H, 'statusS'
	DB	'topFourModify', 00H, 'statusStopFiveModify', 00H, 'statusStop'
	DB	'SixModify', 00H, 'statusStopSevenModify', 00H, 'statusStopEig'
	DB	'htModify', 00H, 'statusPowerOffOneModify', 00H, 'statusPowerO'
	DB	'ffTwoModify', 00H, 'statusPowerOffThreeModify', 00H, 'statusP'
	DB	'owerOffFourModify', 00H, 'statusPowerOffFiveModify', 00H, 'st'
	DB	'atusPowerOffSixModify', 00H, 'statusPowerOffSevenModify', 00H
	DB	'statusPowerOffEightModify', 00H
	ORG $+4
$SG210006 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG210007 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG210008 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG211237 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG211238 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG211239 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_IOService@@3QBIB DD 08H			; qt_meta_data_IOService
	DD	00H
	DD	00H
	DD	00H
	DD	044H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	0162H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	0163H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	0164H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	0165H
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	0166H
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	0167H
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	0168H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	0169H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	016aH
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	016bH
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	016cH
	DD	02H
	DD	08H
	DD	0dH
	DD	00H
	DD	016dH
	DD	02H
	DD	08H
	DD	0eH
	DD	00H
	DD	016eH
	DD	02H
	DD	08H
	DD	0fH
	DD	00H
	DD	016fH
	DD	02H
	DD	08H
	DD	010H
	DD	00H
	DD	0170H
	DD	02H
	DD	08H
	DD	011H
	DD	00H
	DD	0171H
	DD	02H
	DD	08H
	DD	012H
	DD	00H
	DD	0172H
	DD	02H
	DD	08H
	DD	013H
	DD	00H
	DD	0173H
	DD	02H
	DD	08H
	DD	014H
	DD	00H
	DD	0174H
	DD	02H
	DD	08H
	DD	015H
	DD	00H
	DD	0175H
	DD	02H
	DD	08H
	DD	016H
	DD	01H
	DD	0176H
	DD	02H
	DD	08H
	DD	018H
	DD	01H
	DD	0179H
	DD	02H
	DD	08H
	DD	019H
	DD	01H
	DD	017cH
	DD	02H
	DD	08H
	DD	01aH
	DD	01H
	DD	017fH
	DD	02H
	DD	08H
	DD	01bH
	DD	01H
	DD	0182H
	DD	02H
	DD	08H
	DD	01cH
	DD	01H
	DD	0185H
	DD	02H
	DD	08H
	DD	01dH
	DD	01H
	DD	0188H
	DD	02H
	DD	08H
	DD	01eH
	DD	01H
	DD	018bH
	DD	02H
	DD	08H
	DD	01fH
	DD	01H
	DD	018eH
	DD	02H
	DD	08H
	DD	020H
	DD	01H
	DD	0191H
	DD	02H
	DD	08H
	DD	021H
	DD	01H
	DD	0194H
	DD	02H
	DD	08H
	DD	022H
	DD	01H
	DD	0197H
	DD	02H
	DD	08H
	DD	023H
	DD	01H
	DD	019aH
	DD	02H
	DD	08H
	DD	024H
	DD	01H
	DD	019dH
	DD	02H
	DD	08H
	DD	025H
	DD	01H
	DD	01a0H
	DD	02H
	DD	08H
	DD	026H
	DD	01H
	DD	01a3H
	DD	02H
	DD	08H
	DD	027H
	DD	01H
	DD	01a6H
	DD	02H
	DD	08H
	DD	028H
	DD	01H
	DD	01a9H
	DD	02H
	DD	08H
	DD	029H
	DD	01H
	DD	01acH
	DD	02H
	DD	08H
	DD	02aH
	DD	01H
	DD	01afH
	DD	02H
	DD	08H
	DD	02bH
	DD	01H
	DD	01b2H
	DD	02H
	DD	08H
	DD	02cH
	DD	01H
	DD	01b5H
	DD	02H
	DD	08H
	DD	02dH
	DD	01H
	DD	01b8H
	DD	02H
	DD	08H
	DD	02eH
	DD	01H
	DD	01bbH
	DD	02H
	DD	08H
	DD	02fH
	DD	01H
	DD	01beH
	DD	02H
	DD	08H
	DD	030H
	DD	01H
	DD	01c1H
	DD	02H
	DD	08H
	DD	031H
	DD	01H
	DD	01c4H
	DD	02H
	DD	08H
	DD	032H
	DD	01H
	DD	01c7H
	DD	02H
	DD	08H
	DD	033H
	DD	01H
	DD	01caH
	DD	02H
	DD	08H
	DD	034H
	DD	01H
	DD	01cdH
	DD	02H
	DD	08H
	DD	035H
	DD	01H
	DD	01d0H
	DD	02H
	DD	08H
	DD	036H
	DD	01H
	DD	01d3H
	DD	02H
	DD	08H
	DD	037H
	DD	01H
	DD	01d6H
	DD	02H
	DD	08H
	DD	038H
	DD	01H
	DD	01d9H
	DD	02H
	DD	08H
	DD	039H
	DD	01H
	DD	01dcH
	DD	02H
	DD	08H
	DD	03aH
	DD	01H
	DD	01dfH
	DD	02H
	DD	08H
	DD	03bH
	DD	01H
	DD	01e2H
	DD	02H
	DD	08H
	DD	03cH
	DD	01H
	DD	01e5H
	DD	02H
	DD	08H
	DD	03dH
	DD	01H
	DD	01e8H
	DD	02H
	DD	08H
	DD	03eH
	DD	01H
	DD	01ebH
	DD	02H
	DD	08H
	DD	03fH
	DD	01H
	DD	01eeH
	DD	02H
	DD	08H
	DD	040H
	DD	01H
	DD	01f1H
	DD	02H
	DD	08H
	DD	041H
	DD	01H
	DD	01f4H
	DD	02H
	DD	08H
	DD	042H
	DD	01H
	DD	01f7H
	DD	02H
	DD	08H
	DD	043H
	DD	01H
	DD	01faH
	DD	02H
	DD	08H
	DD	044H
	DD	01H
	DD	01fdH
	DD	02H
	DD	08H
	DD	045H
	DD	01H
	DD	0200H
	DD	02H
	DD	08H
	DD	046H
	DD	01H
	DD	0203H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	02bH
	DD	02H
	DD	017H
	DD	00H
	ORG $+4
$SG210328 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG210329 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG210330 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG209684 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG209685 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG209686 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ	; IOService::metaObject
PUBLIC	?qt_metacast@IOService@@UEAAPEAXPEBD@Z		; IOService::qt_metacast
PUBLIC	?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; IOService::qt_metacall
PUBLIC	?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; IOService::qt_static_metacall
PUBLIC	?staticMetaObject@IOService@@2UQMetaObject@@B	; IOService::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?buttonApplyClicked@IOService@@AEAAXXZ:PROC	; IOService::buttonApplyClicked
EXTRN	?nameInputOneModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputOneModify
EXTRN	?nameInputTwoModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputTwoModify
EXTRN	?nameInputThreeModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputThreeModify
EXTRN	?nameInputFourModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputFourModify
EXTRN	?nameInputFiveModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputFiveModify
EXTRN	?nameInputSixModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputSixModify
EXTRN	?nameInputSevenModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputSevenModify
EXTRN	?nameInputEightModify@IOService@@AEAAXXZ:PROC	; IOService::nameInputEightModify
EXTRN	?nameOutputOneModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputOneModify
EXTRN	?nameOutputTwoModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputTwoModify
EXTRN	?nameOutputThreeModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputThreeModify
EXTRN	?nameOutputFourModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputFourModify
EXTRN	?nameOutputFiveModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputFiveModify
EXTRN	?nameOutputSixModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputSixModify
EXTRN	?nameOutputSevenModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputSevenModify
EXTRN	?nameOutputEightModify@IOService@@AEAAXXZ:PROC	; IOService::nameOutputEightModify
EXTRN	?localIPModify@IOService@@AEAAXXZ:PROC		; IOService::localIPModify
EXTRN	?serverIPModify@IOService@@AEAAXXZ:PROC		; IOService::serverIPModify
EXTRN	?portModify@IOService@@AEAAXXZ:PROC		; IOService::portModify
EXTRN	?statusOutputOneModify@IOService@@AEAAXH@Z:PROC	; IOService::statusOutputOneModify
EXTRN	?statusOutputTwoModify@IOService@@AEAAXH@Z:PROC	; IOService::statusOutputTwoModify
EXTRN	?statusOutputThreeModify@IOService@@AEAAXH@Z:PROC ; IOService::statusOutputThreeModify
EXTRN	?statusOutputFourModify@IOService@@AEAAXH@Z:PROC ; IOService::statusOutputFourModify
EXTRN	?statusOutputFiveModify@IOService@@AEAAXH@Z:PROC ; IOService::statusOutputFiveModify
EXTRN	?statusOutputSixModify@IOService@@AEAAXH@Z:PROC	; IOService::statusOutputSixModify
EXTRN	?statusOutputSevenModify@IOService@@AEAAXH@Z:PROC ; IOService::statusOutputSevenModify
EXTRN	?statusOutputEightModify@IOService@@AEAAXH@Z:PROC ; IOService::statusOutputEightModify
EXTRN	?statusInitialInputOneModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputOneModify
EXTRN	?statusInitialInputTwoModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputTwoModify
EXTRN	?statusInitialInputThreeModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputThreeModify
EXTRN	?statusInitialInputFourModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputFourModify
EXTRN	?statusInitialInputFiveModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputFiveModify
EXTRN	?statusInitialInputSixModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputSixModify
EXTRN	?statusInitialInputSevenModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputSevenModify
EXTRN	?statusInitialInputEightModify@IOService@@AEAAXH@Z:PROC ; IOService::statusInitialInputEightModify
EXTRN	?statusMenuOneModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuOneModify
EXTRN	?statusMenuTwoModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuTwoModify
EXTRN	?statusMenuThreeModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuThreeModify
EXTRN	?statusMenuFourModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuFourModify
EXTRN	?statusMenuFiveModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuFiveModify
EXTRN	?statusMenuSixModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuSixModify
EXTRN	?statusMenuSevenModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuSevenModify
EXTRN	?statusMenuEightModify@IOService@@AEAAXH@Z:PROC	; IOService::statusMenuEightModify
EXTRN	?statusRunOneModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunOneModify
EXTRN	?statusRunTwoModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunTwoModify
EXTRN	?statusRunThreeModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunThreeModify
EXTRN	?statusRunFourModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunFourModify
EXTRN	?statusRunFiveModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunFiveModify
EXTRN	?statusRunSixModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunSixModify
EXTRN	?statusRunSevenModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunSevenModify
EXTRN	?statusRunEightModify@IOService@@AEAAXH@Z:PROC	; IOService::statusRunEightModify
EXTRN	?statusStopOneModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopOneModify
EXTRN	?statusStopTwoModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopTwoModify
EXTRN	?statusStopThreeModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopThreeModify
EXTRN	?statusStopFourModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopFourModify
EXTRN	?statusStopFiveModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopFiveModify
EXTRN	?statusStopSixModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopSixModify
EXTRN	?statusStopSevenModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopSevenModify
EXTRN	?statusStopEightModify@IOService@@AEAAXH@Z:PROC	; IOService::statusStopEightModify
EXTRN	?statusPowerOffOneModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffOneModify
EXTRN	?statusPowerOffTwoModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffTwoModify
EXTRN	?statusPowerOffThreeModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffThreeModify
EXTRN	?statusPowerOffFourModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffFourModify
EXTRN	?statusPowerOffFiveModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffFiveModify
EXTRN	?statusPowerOffSixModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffSixModify
EXTRN	?statusPowerOffSevenModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffSevenModify
EXTRN	?statusPowerOffEightModify@IOService@@AEAAXH@Z:PROC ; IOService::statusPowerOffEightModify
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@IOService@@2UQMetaObject@@B DB 030H DUP (?) ; IOService::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@IOService@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@IOService@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN76
	DD	imagerel $LN76+2328
	DD	imagerel $unwind$?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@IOService@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@IOService@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@IOService@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@IOService@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@IOService@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@IOService@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'IOService::staticMetaObject'', COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 388
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B, rax
; Line 389
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_IOService@@3Uqt_meta_stringdata_IOService_t@@B
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B+8, rax
; Line 390
	lea	rax, OFFSET FLAT:?qt_meta_data_IOService@@3QBIB
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B+16, rax
; Line 391
	lea	rax, OFFSET FLAT:?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; IOService::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B+24, rax
; Line 392
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B+32, 0
; Line 393
	mov	QWORD PTR ?staticMetaObject@IOService@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@IOService@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'IOService::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; IOService::qt_static_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 309
$LN76:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 310
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 311
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 313
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 67			; 00000043H
	ja	$LN73@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN75@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 314
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonApplyClicked@IOService@@AEAAXXZ	; IOService::buttonApplyClicked
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 315
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputOneModify@IOService@@AEAAXXZ	; IOService::nameInputOneModify
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 316
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputTwoModify@IOService@@AEAAXXZ	; IOService::nameInputTwoModify
	jmp	$LN2@qt_static_
$LN8@qt_static_:
; Line 317
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputThreeModify@IOService@@AEAAXXZ ; IOService::nameInputThreeModify
	jmp	$LN2@qt_static_
$LN9@qt_static_:
; Line 318
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputFourModify@IOService@@AEAAXXZ	; IOService::nameInputFourModify
	jmp	$LN2@qt_static_
$LN10@qt_static_:
; Line 319
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputFiveModify@IOService@@AEAAXXZ	; IOService::nameInputFiveModify
	jmp	$LN2@qt_static_
$LN11@qt_static_:
; Line 320
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputSixModify@IOService@@AEAAXXZ	; IOService::nameInputSixModify
	jmp	$LN2@qt_static_
$LN12@qt_static_:
; Line 321
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputSevenModify@IOService@@AEAAXXZ ; IOService::nameInputSevenModify
	jmp	$LN2@qt_static_
$LN13@qt_static_:
; Line 322
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameInputEightModify@IOService@@AEAAXXZ ; IOService::nameInputEightModify
	jmp	$LN2@qt_static_
$LN14@qt_static_:
; Line 323
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputOneModify@IOService@@AEAAXXZ	; IOService::nameOutputOneModify
	jmp	$LN2@qt_static_
$LN15@qt_static_:
; Line 324
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputTwoModify@IOService@@AEAAXXZ	; IOService::nameOutputTwoModify
	jmp	$LN2@qt_static_
$LN16@qt_static_:
; Line 325
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputThreeModify@IOService@@AEAAXXZ ; IOService::nameOutputThreeModify
	jmp	$LN2@qt_static_
$LN17@qt_static_:
; Line 326
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputFourModify@IOService@@AEAAXXZ ; IOService::nameOutputFourModify
	jmp	$LN2@qt_static_
$LN18@qt_static_:
; Line 327
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputFiveModify@IOService@@AEAAXXZ ; IOService::nameOutputFiveModify
	jmp	$LN2@qt_static_
$LN19@qt_static_:
; Line 328
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputSixModify@IOService@@AEAAXXZ	; IOService::nameOutputSixModify
	jmp	$LN2@qt_static_
$LN20@qt_static_:
; Line 329
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputSevenModify@IOService@@AEAAXXZ ; IOService::nameOutputSevenModify
	jmp	$LN2@qt_static_
$LN21@qt_static_:
; Line 330
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?nameOutputEightModify@IOService@@AEAAXXZ ; IOService::nameOutputEightModify
	jmp	$LN2@qt_static_
$LN22@qt_static_:
; Line 331
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?localIPModify@IOService@@AEAAXXZ	; IOService::localIPModify
	jmp	$LN2@qt_static_
$LN23@qt_static_:
; Line 332
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?serverIPModify@IOService@@AEAAXXZ	; IOService::serverIPModify
	jmp	$LN2@qt_static_
$LN24@qt_static_:
; Line 333
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?portModify@IOService@@AEAAXXZ		; IOService::portModify
	jmp	$LN2@qt_static_
$LN25@qt_static_:
; Line 334
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputOneModify@IOService@@AEAAXH@Z ; IOService::statusOutputOneModify
	jmp	$LN2@qt_static_
$LN26@qt_static_:
; Line 335
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputTwoModify@IOService@@AEAAXH@Z ; IOService::statusOutputTwoModify
	jmp	$LN2@qt_static_
$LN27@qt_static_:
; Line 336
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputThreeModify@IOService@@AEAAXH@Z ; IOService::statusOutputThreeModify
	jmp	$LN2@qt_static_
$LN28@qt_static_:
; Line 337
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputFourModify@IOService@@AEAAXH@Z ; IOService::statusOutputFourModify
	jmp	$LN2@qt_static_
$LN29@qt_static_:
; Line 338
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputFiveModify@IOService@@AEAAXH@Z ; IOService::statusOutputFiveModify
	jmp	$LN2@qt_static_
$LN30@qt_static_:
; Line 339
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputSixModify@IOService@@AEAAXH@Z ; IOService::statusOutputSixModify
	jmp	$LN2@qt_static_
$LN31@qt_static_:
; Line 340
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputSevenModify@IOService@@AEAAXH@Z ; IOService::statusOutputSevenModify
	jmp	$LN2@qt_static_
$LN32@qt_static_:
; Line 341
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusOutputEightModify@IOService@@AEAAXH@Z ; IOService::statusOutputEightModify
	jmp	$LN2@qt_static_
$LN33@qt_static_:
; Line 342
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputOneModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputOneModify
	jmp	$LN2@qt_static_
$LN34@qt_static_:
; Line 343
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputTwoModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputTwoModify
	jmp	$LN2@qt_static_
$LN35@qt_static_:
; Line 344
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputThreeModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputThreeModify
	jmp	$LN2@qt_static_
$LN36@qt_static_:
; Line 345
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputFourModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputFourModify
	jmp	$LN2@qt_static_
$LN37@qt_static_:
; Line 346
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputFiveModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputFiveModify
	jmp	$LN2@qt_static_
$LN38@qt_static_:
; Line 347
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputSixModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputSixModify
	jmp	$LN2@qt_static_
$LN39@qt_static_:
; Line 348
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputSevenModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputSevenModify
	jmp	$LN2@qt_static_
$LN40@qt_static_:
; Line 349
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusInitialInputEightModify@IOService@@AEAAXH@Z ; IOService::statusInitialInputEightModify
	jmp	$LN2@qt_static_
$LN41@qt_static_:
; Line 350
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuOneModify@IOService@@AEAAXH@Z ; IOService::statusMenuOneModify
	jmp	$LN2@qt_static_
$LN42@qt_static_:
; Line 351
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuTwoModify@IOService@@AEAAXH@Z ; IOService::statusMenuTwoModify
	jmp	$LN2@qt_static_
$LN43@qt_static_:
; Line 352
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuThreeModify@IOService@@AEAAXH@Z ; IOService::statusMenuThreeModify
	jmp	$LN2@qt_static_
$LN44@qt_static_:
; Line 353
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuFourModify@IOService@@AEAAXH@Z ; IOService::statusMenuFourModify
	jmp	$LN2@qt_static_
$LN45@qt_static_:
; Line 354
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuFiveModify@IOService@@AEAAXH@Z ; IOService::statusMenuFiveModify
	jmp	$LN2@qt_static_
$LN46@qt_static_:
; Line 355
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuSixModify@IOService@@AEAAXH@Z ; IOService::statusMenuSixModify
	jmp	$LN2@qt_static_
$LN47@qt_static_:
; Line 356
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuSevenModify@IOService@@AEAAXH@Z ; IOService::statusMenuSevenModify
	jmp	$LN2@qt_static_
$LN48@qt_static_:
; Line 357
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusMenuEightModify@IOService@@AEAAXH@Z ; IOService::statusMenuEightModify
	jmp	$LN2@qt_static_
$LN49@qt_static_:
; Line 358
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunOneModify@IOService@@AEAAXH@Z	; IOService::statusRunOneModify
	jmp	$LN2@qt_static_
$LN50@qt_static_:
; Line 359
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunTwoModify@IOService@@AEAAXH@Z	; IOService::statusRunTwoModify
	jmp	$LN2@qt_static_
$LN51@qt_static_:
; Line 360
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunThreeModify@IOService@@AEAAXH@Z ; IOService::statusRunThreeModify
	jmp	$LN2@qt_static_
$LN52@qt_static_:
; Line 361
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunFourModify@IOService@@AEAAXH@Z ; IOService::statusRunFourModify
	jmp	$LN2@qt_static_
$LN53@qt_static_:
; Line 362
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunFiveModify@IOService@@AEAAXH@Z ; IOService::statusRunFiveModify
	jmp	$LN2@qt_static_
$LN54@qt_static_:
; Line 363
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunSixModify@IOService@@AEAAXH@Z	; IOService::statusRunSixModify
	jmp	$LN2@qt_static_
$LN55@qt_static_:
; Line 364
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunSevenModify@IOService@@AEAAXH@Z ; IOService::statusRunSevenModify
	jmp	$LN2@qt_static_
$LN56@qt_static_:
; Line 365
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusRunEightModify@IOService@@AEAAXH@Z ; IOService::statusRunEightModify
	jmp	$LN2@qt_static_
$LN57@qt_static_:
; Line 366
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopOneModify@IOService@@AEAAXH@Z ; IOService::statusStopOneModify
	jmp	$LN2@qt_static_
$LN58@qt_static_:
; Line 367
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopTwoModify@IOService@@AEAAXH@Z ; IOService::statusStopTwoModify
	jmp	$LN2@qt_static_
$LN59@qt_static_:
; Line 368
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopThreeModify@IOService@@AEAAXH@Z ; IOService::statusStopThreeModify
	jmp	$LN2@qt_static_
$LN60@qt_static_:
; Line 369
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopFourModify@IOService@@AEAAXH@Z ; IOService::statusStopFourModify
	jmp	$LN2@qt_static_
$LN61@qt_static_:
; Line 370
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopFiveModify@IOService@@AEAAXH@Z ; IOService::statusStopFiveModify
	jmp	$LN2@qt_static_
$LN62@qt_static_:
; Line 371
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopSixModify@IOService@@AEAAXH@Z ; IOService::statusStopSixModify
	jmp	$LN2@qt_static_
$LN63@qt_static_:
; Line 372
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopSevenModify@IOService@@AEAAXH@Z ; IOService::statusStopSevenModify
	jmp	$LN2@qt_static_
$LN64@qt_static_:
; Line 373
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusStopEightModify@IOService@@AEAAXH@Z ; IOService::statusStopEightModify
	jmp	$LN2@qt_static_
$LN65@qt_static_:
; Line 374
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffOneModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffOneModify
	jmp	$LN2@qt_static_
$LN66@qt_static_:
; Line 375
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffTwoModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffTwoModify
	jmp	$LN2@qt_static_
$LN67@qt_static_:
; Line 376
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffThreeModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffThreeModify
	jmp	$LN2@qt_static_
$LN68@qt_static_:
; Line 377
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffFourModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffFourModify
	jmp	SHORT $LN2@qt_static_
$LN69@qt_static_:
; Line 378
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffFiveModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffFiveModify
	jmp	SHORT $LN2@qt_static_
$LN70@qt_static_:
; Line 379
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffSixModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffSixModify
	jmp	SHORT $LN2@qt_static_
$LN71@qt_static_:
; Line 380
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffSevenModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffSevenModify
	jmp	SHORT $LN2@qt_static_
$LN72@qt_static_:
; Line 381
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?statusPowerOffEightModify@IOService@@AEAAXH@Z ; IOService::statusPowerOffEightModify
$LN73@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 385
	add	rsp, 56					; 00000038H
	ret	0
	npad	1
$LN75@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
	DD	$LN17@qt_static_
	DD	$LN18@qt_static_
	DD	$LN19@qt_static_
	DD	$LN20@qt_static_
	DD	$LN21@qt_static_
	DD	$LN22@qt_static_
	DD	$LN23@qt_static_
	DD	$LN24@qt_static_
	DD	$LN25@qt_static_
	DD	$LN26@qt_static_
	DD	$LN27@qt_static_
	DD	$LN28@qt_static_
	DD	$LN29@qt_static_
	DD	$LN30@qt_static_
	DD	$LN31@qt_static_
	DD	$LN32@qt_static_
	DD	$LN33@qt_static_
	DD	$LN34@qt_static_
	DD	$LN35@qt_static_
	DD	$LN36@qt_static_
	DD	$LN37@qt_static_
	DD	$LN38@qt_static_
	DD	$LN39@qt_static_
	DD	$LN40@qt_static_
	DD	$LN41@qt_static_
	DD	$LN42@qt_static_
	DD	$LN43@qt_static_
	DD	$LN44@qt_static_
	DD	$LN45@qt_static_
	DD	$LN46@qt_static_
	DD	$LN47@qt_static_
	DD	$LN48@qt_static_
	DD	$LN49@qt_static_
	DD	$LN50@qt_static_
	DD	$LN51@qt_static_
	DD	$LN52@qt_static_
	DD	$LN53@qt_static_
	DD	$LN54@qt_static_
	DD	$LN55@qt_static_
	DD	$LN56@qt_static_
	DD	$LN57@qt_static_
	DD	$LN58@qt_static_
	DD	$LN59@qt_static_
	DD	$LN60@qt_static_
	DD	$LN61@qt_static_
	DD	$LN62@qt_static_
	DD	$LN63@qt_static_
	DD	$LN64@qt_static_
	DD	$LN65@qt_static_
	DD	$LN66@qt_static_
	DD	$LN67@qt_static_
	DD	$LN68@qt_static_
	DD	$LN69@qt_static_
	DD	$LN70@qt_static_
	DD	$LN71@qt_static_
	DD	$LN72@qt_static_
?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; IOService::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; IOService::qt_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 411
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 412
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 413
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 414
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 415
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 416
	cmp	DWORD PTR _id$[rsp], 68			; 00000044H
	jge	SHORT $LN5@qt_metacal
; Line 417
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@IOService@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; IOService::qt_static_metacall
$LN5@qt_metacal:
; Line 418
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 68					; 00000044H
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 419
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 420
	cmp	DWORD PTR _id$[rsp], 68			; 00000044H
	jge	SHORT $LN7@qt_metacal
; Line 421
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 422
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 68					; 00000044H
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 424
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 425
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@IOService@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; IOService::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@IOService@@UEAAPEAXPEBD@Z PROC		; IOService::qt_metacast
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 403
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 404
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 405
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_IOService@@3Uqt_meta_stringdata_IOService_t@@B+1704
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 406
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 407
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 408
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@IOService@@UEAAPEAXPEBD@Z ENDP		; IOService::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ PROC	; IOService::metaObject
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 398
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 399
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@IOService@@2UQMetaObject@@B ; IOService::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 400
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@IOService@@UEBAPEBUQMetaObject@@XZ ENDP	; IOService::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.12.3\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 428
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_ioservice.cpp
; Line 428
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
