; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG202916 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG202917 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG202918 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG203238 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG203239 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG203240 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG204475 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+12
$SG204476 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG204477 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_CycleSetting@@3Uqt_meta_stringdata_CycleSetting_t@@B DD 0ffffffffH ; qt_meta_stringdata_CycleSetting
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000150H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000145H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000013fH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	0000000000000128H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000123H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000011dH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	0000000000000116H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	000000000000010fH
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	000000000000010aH
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000104H
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	00000000000000feH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000f7H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000f2H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	00000000000000edH
	DB	'CycleSetting', 00H, 'buttonSureClicked', 00H, 00H, 'butt'
	DB	'onClearClicked', 00H, 'buttonZeroClicked', 00H, 'buttonOneCli'
	DB	'cked', 00H, 'buttonTwoClicked', 00H, 'buttonThreeClicked', 00H
	DB	'buttonFourClicked', 00H, 'buttonFiveClicked', 00H, 'buttonSix'
	DB	'Clicked', 00H, 'buttonSevenClicked', 00H, 'buttonEightClicked'
	DB	00H, 'buttonNineClicked', 00H
	ORG $+1
$SG202594 DB	'E:\Qt\5.12.3\msvc2015_64\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG202595 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG202596 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_data_CycleSetting@@3QBIB DD 08H		; qt_meta_data_CycleSetting
	DD	00H
	DD	00H
	DD	00H
	DD	0cH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	04aH
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	04bH
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	04cH
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	04dH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	04eH
	DD	02H
	DD	08H
	DD	07H
	DD	00H
	DD	04fH
	DD	02H
	DD	08H
	DD	08H
	DD	00H
	DD	050H
	DD	02H
	DD	08H
	DD	09H
	DD	00H
	DD	051H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	052H
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	053H
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	054H
	DD	02H
	DD	08H
	DD	0dH
	DD	00H
	DD	055H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ ; CycleSetting::metaObject
PUBLIC	?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z	; CycleSetting::qt_metacast
PUBLIC	?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; CycleSetting::qt_metacall
PUBLIC	?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleSetting::qt_static_metacall
PUBLIC	?staticMetaObject@CycleSetting@@2UQMetaObject@@B ; CycleSetting::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?buttonSureClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonSureClicked
EXTRN	?buttonClearClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonClearClicked
EXTRN	?buttonZeroClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonZeroClicked
EXTRN	?buttonOneClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonOneClicked
EXTRN	?buttonTwoClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonTwoClicked
EXTRN	?buttonThreeClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonThreeClicked
EXTRN	?buttonFourClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonFourClicked
EXTRN	?buttonFiveClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonFiveClicked
EXTRN	?buttonSixClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonSixClicked
EXTRN	?buttonSevenClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonSevenClicked
EXTRN	?buttonEightClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonEightClicked
EXTRN	?buttonNineClicked@CycleSetting@@AEAAXXZ:PROC	; CycleSetting::buttonNineClicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@CycleSetting@@2UQMetaObject@@B DB 030H DUP (?) ; CycleSetting::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN20
	DD	imagerel $LN20+288
	DD	imagerel $unwind$?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@CycleSetting@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@CycleSetting@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@CycleSetting@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@CycleSetting@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@CycleSetting@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'CycleSetting::staticMetaObject'', COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 129
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B, rax
; Line 130
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_CycleSetting@@3Uqt_meta_stringdata_CycleSetting_t@@B
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B+8, rax
; Line 131
	lea	rax, OFFSET FLAT:?qt_meta_data_CycleSetting@@3QBIB
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B+16, rax
; Line 132
	lea	rax, OFFSET FLAT:?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleSetting::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B+24, rax
; Line 133
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B+32, 0
; Line 134
	mov	QWORD PTR ?staticMetaObject@CycleSetting@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@CycleSetting@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'CycleSetting::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; CycleSetting::qt_static_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 105
$LN20:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 106
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 107
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 11
	ja	$LN17@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN19@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 110
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSureClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonSureClicked
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 111
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonClearClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonClearClicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 112
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonZeroClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonZeroClicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 113
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonOneClicked@CycleSetting@@AEAAXXZ	; CycleSetting::buttonOneClicked
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 114
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonTwoClicked@CycleSetting@@AEAAXXZ	; CycleSetting::buttonTwoClicked
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 115
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonThreeClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonThreeClicked
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 116
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonFourClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonFourClicked
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 117
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonFiveClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonFiveClicked
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 118
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSixClicked@CycleSetting@@AEAAXXZ	; CycleSetting::buttonSixClicked
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 119
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonSevenClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonSevenClicked
	jmp	SHORT $LN2@qt_static_
$LN15@qt_static_:
; Line 120
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonEightClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonEightClicked
	jmp	SHORT $LN2@qt_static_
$LN16@qt_static_:
; Line 121
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?buttonNineClicked@CycleSetting@@AEAAXXZ ; CycleSetting::buttonNineClicked
$LN17@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 126
	add	rsp, 56					; 00000038H
	ret	0
	npad	3
$LN19@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
	DD	$LN15@qt_static_
	DD	$LN16@qt_static_
?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CycleSetting::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; CycleSetting::qt_metacall
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 152
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 153
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 154
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 155
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 156
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 157
	cmp	DWORD PTR _id$[rsp], 12
	jge	SHORT $LN5@qt_metacal
; Line 158
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@CycleSetting@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CycleSetting::qt_static_metacall
$LN5@qt_metacal:
; Line 159
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 12
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 160
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 161
	cmp	DWORD PTR _id$[rsp], 12
	jge	SHORT $LN7@qt_metacal
; Line 162
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 163
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 12
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 165
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 166
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@CycleSetting@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CycleSetting::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z PROC		; CycleSetting::qt_metacast
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 144
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 145
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 146
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_CycleSetting@@3Uqt_meta_stringdata_CycleSetting_t@@B+336
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 147
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 148
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 149
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@CycleSetting@@UEAAPEAXPEBD@Z ENDP		; CycleSetting::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ PROC	; CycleSetting::metaObject
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 139
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 140
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@CycleSetting@@2UQMetaObject@@B ; CycleSetting::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 141
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@CycleSetting@@UEBAPEBUQMetaObject@@XZ ENDP	; CycleSetting::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File e:\qt\5.12.3\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 169
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\lx\desktop\moldmachine\moldmachine\moldmachine\x64\debug\moc\moc_cyclesetting.cpp
; Line 169
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
